#!/bin/bash
# Copyright (C) 2020 Satoshi Konno. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

makefiles=(
"include"
"lib/unix"
"test/unix"
"bin/fdinfo/unix"
"bin/fdwrite/unix"
"bin/fdread/unix"
"bin/fdimg/unix"
)

for makefile in "${makefiles[@]}"
do
    pushd $makefile && ./Makefile.am.build > Makefile.am && popd
done

if [ ! -d config ]; then
    mkdir config
fi
if [ ! -d autom4te.cache ]; then
	rm -rf autom4te.cache/*
fi

aclocal
autoheader
automake --foreign --add-missing --copy
autoconf 
