name: fdtools
type: app
base: core20
version: git
summary: Fdtools is a utility package for floppy disk drives and images.
description: |
  Fdtools is a utility package for floppy disk drives and images on multi-platform.
license: "Apache-2.0"

grade: stable
confinement: strict

apps:
  fdtools:
    command: fddump $SNAP/bin/fddump/unix/fddump
    command: fdinfo $SNAP/bin/fddump/unix/fdinfo

parts:
  fdtools:
    plugin: autotools
    source: https://github.com/cybergarage/fdtools
    source-type: git
